#!/user/bin/env python
# -*- coding: cp1252 -*-
# stats.py
# Created by Keith Marrs-Olson
# Credit to where credit is due
#   From The Rifter #63 pg 59
#   The Handy Dandy Random Adventure Generator
#   For Beyond the Supernatural™
#   By Chai Gallahun

people = {#People (Main & Supporting Characters)
    1:"Scientist",
    2:"Biologist",
    3:"Archaeologist",
    4:"Paleontologist",
    5:"Philanthropist",
    6:"Physicist",
    7:"Psychologist",
    8:"Psychiatrist",
    9:"Astronomer",
    10:"Escaped criminal",
    11:"Escaped mental patient",
    12:"Escaped serial killer",
    13:"Soldier",
    14:"Sailor",
    15:"Airman",
    16:"Marine",
    17:"Air traffic controller",
    18:"Truck driver",
    19:"Park ranger",
    20:"Paranormal investigator",
    21:"Doctor",
    22:"Surgeon",
    23:"Medical Student",
    24:"Physician’s assistant (PA)",
    25:"Nurse",
    26:"Grief counselor",
    27:"Veterinarian",
    28:"Emergency medical technician",
    29:"Ambulance crew/driver",
    30:"Firefighter/crew",
    31:"Police officer",
    32:"911 operator",
    33:"Conspiracy theorist",
    34:"Drug addict",
    35:"Airline pilot",
    36:"Police detective",
    37:"Police commissioner",
    38:"Police chief",
    39:"City mayor",
    40:"Government official",
    41:"Military contractor",
    42:"Investigative journalist",
    43:"Newspaper reporter",
    44:"Newspaper editor",
    45:"Pharmacist",
    46:"Chemist",
    47:"Professor",
    48:"Teacher",
    49:"Construction worker",
    50:"Convenience store clerk",
    51:"Chef",
    52:"Diner cook",
    53:"Professional athlete",
    54:"Landscaper",
    55:"Business owner",
    56:"Professional burglar",
    57:"Chief Executive Officer(CEO)",
    58:"Architect",
    59:"Professional movie actor",
    60:"Professional stage magician",
    61:"Composer",
    62:"Farmer",
    63:"Moviemaker",
    64:"Government contractor",
    65:"Military veteran",
    66:"Novelist",
    67:"Activist",
    68:"Active-duty military professional",
    69:"Gang member",
    70:"FBI agent",
    71:"FBI special agent",
    72:"FBI special agent-in-charge",
    73:"Serial killer",
    74:"Drug-dealer",
    75:"Plumber",
    76:"Con-artist",
    77:"Pest-controller",
    78:"Dance club manager",
    79:"Exotic dancer",
    80:"Professional escort",
    81:"Aspiring megalomaniac",
    82:"Son/daughter of wealthy elite",
    83:"Wealthy secret society member",
    84:"Taxi driver",
    85:"Waitress/waiter",
    86:"Minister",
    87:"Preacher",
    88:"Sociopath in the guise of a (roll on this table again, ignoring this result)",
    89:"Food truck worker",
    90:"Wiccan high priest/priestess",
    91:"Cultist",
    92:"Cult leader",
    93:"Police officer",
    94:"State trooper",
    95:"Psychiatric patient",
    96:"Professional clown",
    97:"Private investigator",
    98:"Psychopath",
    99:"Savant genius",
    100:"Psychic Prodigy",}

place = { #Places (Primary and Supporting Locations)
    1:"Secret underground government facility",
    2:"Meat-packing plant",
    3:"State highway motor lodge",
    4:"Primitive national forest camping area",
    5:"Interstate rest area",
    6:"Municipal airport",
    7:"City museum",
    8:"Beach house",
    9:"Multiplex theater",
    10:"Obscure mining complex",
    11:"Liquor store",
    12:"Bus station",
    13:"International airport",
    14:"4D4-story downtown building",
    15:"Gas station & convenience store",
    16:"Automotive repair garage",
    17:"Coffee house",
    18:"High-end (organic) grocery market",
    19:"Modern hospital",
    20:"Regional library",
    21:"Church",
    22:"Mausoleum",
    23:"State sanitarium",
    24:"Movie set",
    25:"Ranger station",
    26:"Police precinct",
    27:"Fire station",
    28:"Auto graveyard/junkyard",
    29:"Cemetery",
    30:"Lakeside campground",
    31:"City aquarium",
    32:"Traveling carnival (fairgrounds)",
    33:"Magic/mystic shop",
    34:"A secured Joint Intelligence Operations Center (JIOC)",
    35:"New age shop",
    36:"Funeral home (or crematorium)",
    37:"Five-star restaurant",
    38:"Sewer tunnels",
    39:"Tourist (or unexplored) cavern(s)",
    40:"Modern RV camping area",
    41:"Department store",
    42:"Traditional indoor shopping mall",
    43:"Outdoor fashion park mall",
    44:"Mansion/Estate",
    45:"24 hour breakfast diner",
    46:"Housing project(s)",
    47:"Middle/upper-class home",
    48:"Radio station",
    49:"Sorority house",
    50:"Fraternity house",
    51:"University library",
    52:"Industrial office complex",
    53:"5D20-story Skyscraper",
    54:"Regional hydroelectric dam",
    55:"Nuclear power plant",
    56:"Apartment complex",
    57:"Marina",
    58:"Cruise ship at sea",
    59:"Beached cruise ship",
    60:"Beach house",
    61:"Large, interstate travel complex (grand truck stop)",
    62:"Liquor store",
    63:"Winery (vineyard)",
    64:"Bar & grill",
    65:"A wooded island amidst a junction of rivers",
    66:"Popular chain bookstore",
    67:"Arcane/mystical bookstore",
    68:"Bed and breakfast",
    69:"Active or abandoned church",
    70:"Fast-food restaurant",
    71:"Pizza shop",
    72:"City pier",
    73:"Civil War national battlefield park",
    74:"Native American reservation",
    75:"Army fort",
    76:"Air Force base",
    77:"Naval base",
    78:"Marine Corps base",
    79:"Coast Guard station",
    80:"Shipyard",
    81:"Port district",
    82:"Oil refinery",
    83:"Gulf oil rig",
    84:"Isolated stone quarry",
    85:"Horse ranch (with farm buildings)",
    86:"University (or military academy) campus",
    87:"Stadium (sports complex)",
    88:"Lakeshore",
    89:"Riverbank",
    90:"Planetarium",
    91:"Public high school",
    92:"Community college campus",
    93:"Circus (D4+1 rings)",
    94:"Local network news station",
    95:"Main Street U.S.A",
    96:"City hall (or courthouse)",
    97:"Newspaper office",
    98:"Clandestine government lab",
    99:"Coal (or gold) mine",
    100:"Correctional facility (prison)",}

Stage = { #Scary Things - Conditions (Stage Dressing)
    1:"Midnight",
    2:"Operational hours",
    3:"A wild party",
    4:"A harsh rainfall",
    5:"A misty drizzle",
    6:"A thick fog",
    7:"A raging torrent",
    8:"A devastating tsunami",
    9:"An incapacitating blizzard",
    10:"The storm of the century",
    11:"A wicked ice storm",
    12:"A blackout",
    13:"Terrible flooding",
    14:"Terrible drought",
    15:"Sunrise",
    16:"Sundown",
    17:"Twilight",
    18:"Halloween",
    19:"A violent incident",
    20:"A robbery",
    21:"An investigation",
    22:"A plague",
    23:"An outbreak",
    24:"A massive meteor shower",
    25:"An earthquake",
    26:"A volcanic eruption",
    27:"A significant meteor impact",
    28:"A comet’s passing",
    29:"A cometary impact",
    30:"An asteroid’s passing",
    31:"An asteroid impact",
    32:"A political murder",
    33:"A serial killing",
    34:"A murder",
    35:"A terrorist attack",
    36:"A national military coup",
    37:"A viral outbreak",
    38:"Atmospheric sonic booms",
    39:"A medical crisis",
    40:"An earthquake",
    41:"Earthquakes",
    42:"An aftershock",
    43:"Aftershocks",
    44:"A devastating series of crippling aftershocks",
    45:"A quarantine",
    46:"An outrageous office party",
    47:"A special spring equinox",
    48:"A special summer solstice",
    49:"A special autumn/fall equinox",
    50:"A special winter solstice",
    51:"A lunar eclipse",
    52:"A solar eclipse",
    53:"A crescent moon",
    54:"A waning moon",
    55:"A waxing moon",
    56:"A full moon",
    57:"A new moon",
    58:"A solar flare",
    59:"Solar flares",
    60:"A massive onslaught of devastating solar flares",
    61:"A funeral",
    62:"A state of martial law",
    63:"A riot",
    64:"A militia uprising",
    65:"A government “false-flag” operation",
    66:"Supernatural portals opening",
    67:"2D12 “city-killer” meteors striking nearby major populationcenters",
    68:"Nuclear terrorism",
    69:"A limited state-to-state nuclear exchange (attack)",
    70:"A dirty-bomb attack",
    71:"A suicide bomber attack",
    72:"A mad gunman attack",
    73:"High-speed vehicle pursuit",
    74:"A domestic military exercise",
    75:"National Guard military exercise",
    76:"A birthday (party)",
    77:"A wedding ceremony",
    78:"A monster sighting",
    79:"A UFO sighting",
    80:"A home invasion",
    81:"A carjacking",
    82:"A vehicle breakdown",
    83:"A massive vehicle pileup",
    84:"A national tragedy",
    85:"A deadly clown attack",
    86:"Massive tremors",
    87:"Severe glacial melting",
    88:"A loss of satellite communication",
    89:"An electromagnetic pulse (EMP) attack",
    90:"An FBI investigation",
    91:"A foreign military invasion (attack)",
    92:"A rash of unexplained murders",
    93:"A series of unexplained disappearances",
    94:"A missing-persons investigation",
    95:"A criminal investigation",
    96:"A series of devastating sinkholes",
    97:"A flap of UFO sightings and close encounters of various kinds",
    98:"A celestial display of a supernova",
    99:"A visible manifestation of ley lines and ley line nexuses",
    100:"The Apocalypse (End of Days) involving ",}

EOD = { #The Apocalypse (End of Days) ^
    1:"The opening of dimensional portals",
    2:"The rise of the dead (zombies)",
    3:"An alien invasion",
    4:"The return of the Old Ones",
    5:"The onset of World War 3",
    6:"Massive earthquakes and volcanic eruptions",
    7:"A global super-storm",
    8:"Every person developing psychic power (those who already have it develop another ability)",}

SThing = { #Scary Things Threats(Things That Went Bump in the Night)
    1:"Giant snake",
    2:"Giant hound",
    3:"Giant mouse",
    4:"Giant rat",
    5:"Giant bat",
    6:"Giant wolf",
    7:"Giant boar",
    8:"Giant pig",
    9:"Grizzly bear",
    10:"Giant wolverine",
    11:"Hydra",
    12:"Pack of rabid hounds",
    13:"Wererat",
    14:"Werebat",
    15:"Werewolf",
    16:"Wereboar",
    17:"Werepig",
    18:"Werebear",
    19:"Werewolverine",
    20:"Mammoth",
    21:"Saber-toothed tiger",
    22:"Giant cat",
    23:"Giant panther",
    24:"Giant lion",
    25:"Giant Bengal tiger",
    26:"Thunderbird(s)",
    27:"Giant poisonous spiders",
    28:"Giant poisonous spider colony",
    29:"Giant ravenous fire ants",
    30:"Giant ravenous fire ant colony",
    31:"Giant termites",
    32:"Giant termite colony",
    33:"Giant lethal mosquitos",
    34:"Giant contagion flies",
    35:"Giant maggots (that can explode)",
    36:"Giant bees",
    37:"Giant yellow jackets",
    38:"Giant electrical hornets",
    39:"Giant angry wasps",
    40:"Giant devastating locusts",
    41:"Giant, blood-sucking leeches",
    42:"Giant moths",
    43:"Giant caterpillars",
    44:"Giant carnivorous plants",
    45:"Giant (flying & poisonous) jellyfish",
    46:"Giant alligator",
    47:"Giant flying manta ray",
    48:"Devil",
    49:"Hellion",
    50:"Frost Devil",
    51:"Devil Lord",
    52:"Devil Queen",
    53:"Demon",
    54:"Succubus",
    55:"Demon lord",
    56:"Demon queen",
    57:"Lich",
    58:"Vampire",
    59:"Vampiress",
    60:"Vampire assistant (roll on Table 1: People)",
    61:"Vampiress assistant (roll on Table 1: People)",
    62:"Ghoul",
    63:"Ghost",
    64:"Haunt",
    65:"Spectre",
    66:"Apparition",
    67:"Poltergeist",
    68:"Ghost",
    69:"Banshee",
    70:"Animated corpse",
    71:"Zombie(s)",
    72:"Sasquatch",
    73:"Bigfoot",
    74:"Skunk ape",
    75:"Reptoid(s)",
    76:"Lizard man(men)",
    77:"Winged draconian reptoid(s)",
    78:"Reptoid queen",
    79:"Reptoid mage",
    80:"Reptoid lord",
    81:"Headless motorcyclist",
    82:"Mummy",
    83:"University mummy",
    84:"Attic mummy",
    85:"Pharaoh mummy",
    86:"Queen of the Mummies",
    87:"Animated (demonic) scarecrow",
    88:"Animated, wooden Native American statue (with tomahawk)",
    89:"Basic golem (granite, clay, mud, etc.)",
    90:"Complex golem (flesh, bone, vine, glass, etc.)",
    91:"Air Elemental (dust devil, tornado, etc.)",
    92:"Water Elemental (hurricane, ice, etc.)",
    93:"Fire Elemental (ash, ember, firestorm, etc.)",
    94:"Earth Elemental (sand, mud, landslide, etc.)",
    95:"Doppelganger/shape-shifter",
    96:"Evil clown entity",
    97:"Nightmare entity",
    98:"An avatar of an Old One in the guise of (roll on Table 1: People)",
    99:"The emergence of an Old One",}
    #100:Roll 2D4 more times on this table

Weather = { #Cloudy with a Chance for Horror (Weather)
    1:"Tornado watch",
    2:"Tornado warning",
    3:"Tornados imminent",
    4:"F1 tornado",
    5:"F2 tornado",
    6:"F3 tornado",
    7:"F4 tornado",
    8:"F5 tornado",
    9:"Misty drizzle",
    10:"Drizzle",
    11:"Light sprinkling",
    12:"Sprinkles",
    13:"Light fog",
    14:"Fog",
    15:"Heavy fog",
    16:"Thick, clammy fog",
    17:"Light rain",
    18:"Moderate rain",
    19:"Heavy rain",
    20:"Torrential rain",
    21:"Cloudburst rain",
    22:"Thunderstorm rain",
    23:"Thunderstorm",
    24:"Distant lightning",
    25:"Heat lightning",
    26:"Lightning storm",
    27:"Purple lightning storm",
    28:"Antimatter lightning storm",
    29:"Electromagnetic lightning storm",
    30:"Severe thunderstorm",
    31:"Storm of the century",
    32:"Nor’easter",
    33:"Storm flooding",
    34:"Slight flooding",
    35:"Flooding",
    36:"Moderate flooding",
    37:"Heavy flooding",
    38:"Torrential flooding",
    39:"Hurricane surge flooding",
    40:"Tropical depression",
    41:"Hurricane",
    42:"Minor hurricane",
    43:"Major hurricane",
    44:"Severe hurricane",
    45:"Devastating hurricane",
    46:"Catastrophic hurricane",
    47:"Heat advisory",
    48:"Heat warning",
    49:"Solar flare",
    50:"Electromagnetic pulse-level solar flare",
    51:"Drought",
    52:"Severe drought",
    53:"A noxious rain",
    54:"Gusty dust",
    55:"Dust storm",
    56:"A storm of microscopic glass particles (deadly to those exposed)",
    57:"Sandstorm",
    58:"A rain of blood (a rain of unidentified red liquid)",
    59:"A rain of poisonous jellyfish",
    60:"A shower of poisonous spiders",
    61:"A rain of greenish goo (unidentified organic material)",
    62:"A rain of fish",
    63:"A rain smelling of decomposing corpses",
    64:"Strong wind",
    65:"A rain of frogs",
    66:"Gusty winds",
    67:"Severe gusts",
    68:"Partly cloudy",
    69:"Mostly cloudy",
    70:"Overcast",
    71:"Partly sunny",
    72:"Mostly sunny",
    73:"Severe hail",
    74:"Snowstorm",
    75:"Lightning snowstorm",
    76:"Antimatter electromagnetic lightning snowstorm",
    77:"Snow flurries",
    78:"Light snow (D4 inches)",
    79:"Moderate snow (6D4 inches)",
    80:"Heavy snow (6D8 inches)",
    81:"Blizzard (2D4+1 feet)",
    82:"Heavy blizzard (4D4+2 feet)",
    83:"Sleet",
    84:"Heavy sleet",
    85:"Frozen rain",
    86:"Icy rain",
    87:"Ice storm",
    88:"High-magnitude ice-lightning storm",
    89:"Severe hail (2D4 inches/3D6+2 cm in diameter)",
    90:"Ice storm aerial tsunami",
    91:"Aerial firestorm wave-front",
    92:"Aerial firestorm tsunami",
    93:'Ground-level horizontal tornado (2D4 miles/3",2-12",8 km wide)',
    94:"Electromagnetic tornado (2D4 miles in diameter)",
    95:"Petrol-based flaming rain",
    96:"Searing acid rain cloudburst",
    97:'Waterspout (D4 miles/1",6-6",4 km wide)',
    98:"Fire twister (D4 miles wide)",}
    #99:"Roll D4+1 more times on this table",
    #100:"Roll 2D4+1 more times on this table",
